import colors from '@conf/theme/colorThemes/color';
import ColorTheme from '@conf/theme/colorThemes/types';

const lightTheme: ColorTheme = {
    bg: colors.brandBg,
    bgSurface: colors.gray400,
    bgSurfaceNewNav: colors.gray200,
    bgSurfaceDarker: colors.gray100,
    bgSurfaceBrand: colors.brandAccentTertiary,
    bgSurfaceBrandHover: colors.brandAccentSecondary,
    buttonSurfaceBrandHover: colors.brandPrimaryHover,
    bgDisabled: colors.gray400,
    bgSurfaceError: colors.brandRedBg,
    bgSurfaceErrorHover: colors.wine100,
    bgSurfaceInfo: colors.brandPrimarySubtle,
    bgSurfaceInformationHover: colors.brandAccentSecondary,
    bgSurfaceSuccess: colors.brandGreenBg,
    bgSurfaceSuccessHover: colors.green100,
    bgSurfaceWarning: colors.brandYellowBg,
    bgSurfaceWarningHover: colors.yellow200,
    bgHover: colors.gray400,
    text: colors.brandText,
    textSecondary: colors.brandDarkGrey,
    textTertiary: colors.brandLightGrey,
    textBrand: colors.brandPrimary,
    textBrandOnBgFill: colors.gray0,
    textOnFillBrand: colors.gray0,
    textOnFillSuccess: colors.gray0,
    textOnFillError: colors.gray0,
    textOnFillWarning: colors.gray0,
    textOnFillInfo: colors.gray0,
    textOnFillDefault: colors.gray0,
    textDisabled: colors.gray600,
    textError: colors.brandRedText,
    textInformation: colors.brandPrimary,
    textSuccess: colors.brandGreenText,
    textWarning: colors.brandYellowText,
    textOnSurfaceError: colors.brandRedText,
    textOnSurfaceInformation: colors.brandPrimary,
    textOnSurfaceSuccess: colors.brandGreenText,
    textOnSurfaceWarning: colors.brandYellowText,
    hyperlinks: colors.brandPrimary,
    icon: colors.brandDarkGrey,
    iconBrand: colors.brandPrimary,
    iconError: colors.brandRedText,
    iconInformation: colors.brandPrimary,
    iconSuccess: colors.brandGreenText,
    iconWarning: colors.brandYellowText,
    iconOnFillBrand: colors.gray0,
    buttonFillBrand: colors.brandPrimary,
    buttonFillFocus: colors.brandPrimary,
    buttonSurfaceBrandFocus: colors.brandAccentSecondary,
    buttonSurfaceSecondaryHover: colors.brandAccentTertiary,
    radioButtonBorder: colors.gray600,
    radioButtonDotFill: colors.gray0,
    radioButtonDotDisabled: colors.gray500,
    borderCheckbox: colors.gray500,
    avatarBorderBrand: colors.brandAccentSecondary,
    avatarBorderInformation: colors.brandAccentSecondary,
    border: colors.gray100,
    borderBrand: colors.brandPrimary,
    borderBrandFocused: colors.brandPrimaryDisabled,
    borderBrandInverse: colors.brandAccentTertiary,
    borderDisabled: colors.gray600,
    borderInformation: colors.brandPrimary,
    borderInformationInverse: colors.brandPrimarySubtle,
    borderError: colors.brandRedText,
    borderSuccess: colors.brandGreenText,
    borderWarning: colors.brandYellowText,
    borderWhite: colors.gray0,
    // Interactive states: Hover
    textHover: colors.brandPrimaryHover,
    iconHover: colors.brandPrimaryHover,
    borderHover: colors.brandPrimaryDisabled,
    // Interactive states: Active / Pressed
    bgActive: colors.brandAccentTertiary,
    textActive: colors.brandPrimaryActive,
    borderActive: colors.brandPrimary,
    // Interactive states: Selected
    bgSelected: colors.brandAccentTertiary,
    bgSelectedSubtle: 'rgba(55, 193, 206, 0.06)',
    textSelected: colors.brandPrimary,
    iconSelected: colors.brandPrimary,
    borderSelected: colors.brandPrimary,
    // Interactive states: Focus
    borderFocused: colors.gray500,
    // Interactive states: Disabled
    iconDisabled: colors.gray500,
    bgSurfaceDisabled: colors.gray400,
    // Shadows
    shadowXs: '0 1px 2px 0 rgba(33, 23, 95, 0.04)',
    shadowSm: '0 2px 4px 0 rgba(33, 23, 95, 0.06)',
    shadowMd: '0 0 24px 0 rgba(0, 0, 0, 0.10)',
    shadowLg: '0 4px 12px 0 rgba(9, 1, 61, 0.12)',
    shadowXl: '0 4px 28px 0 rgba(9, 1, 61, 0.14)',
    shadowFocus: '0px 0px 0px 1px rgba(139, 135, 157, 0.08)',
    shadowFocusBrand: '0px 0px 0px 1px rgba(108, 71, 255, 0.08)',
    shadowInset: 'inset 0px 1px 3px rgba(0, 0, 0, 0.08)',
    shadowNavbar: '0px 2px 10px rgba(0, 0, 0, 0.08)',
    shadowDropBrandColor: colors.brandPrimaryShadow,
    shadowViewSelect: '0px 525px 20px 500px rgba(0, 0, 0, 0.12), 0px 65px 60px 0px rgba(0, 0, 0, 0.12)',

    // Overlays
    overlayLight: 'rgba(0, 0, 0, 0.05)',
    overlayMedium: 'rgba(0, 0, 0, 0.15)',
    overlayHeavy: 'rgba(0, 0, 0, 0.45)',
    overlayOnBrand: 'rgba(255, 255, 255, 0.2)',
    overlayMask: 'rgba(0, 0, 0, 0.5)',
    overlayDropShadow: 'rgba(0, 0, 0, 0.25)',
    // Inputs / Forms
    bgInput: colors.gray0,
    bgInputDisabled: colors.gray400,
    borderInput: colors.gray100,
    borderInputFocus: colors.brandPrimary,
    textPlaceholder: colors.brandLightGrey,
    // Scrollbar
    scrollbarTrack: 'transparent',
    scrollbarThumb: colors.gray100,
    scrollbarThumbHover: colors.gray500,
    scrollbarThumbOnDarkBg: colors.gray500,
    // Code blocks
    bgCode: colors.gray200,
    bgCodeBlock: colors.gray200,
    // Highlight
    bgHighlight: '#ffe58f',
    // Tooltip
    bgTooltip: colors.gray1000,
    // Brand gradients
    brandGradient: 'radial-gradient(115.48% 144.44% at 50% -44.44%, #5BD0DA 38.97%, #37C1CE 100%)',
    brandGradientSelected: 'linear-gradient(180deg, #5BD0DA 20%, #2BA8B4 80%)',
    // Skeleton / Loading
    bgSkeleton: colors.gray100,
    bgSkeletonShimmer: colors.gray200,
    chartsWineHigh: colors.wine600,
    chartsWineMedium: colors.wine400,
    chartsWineLow: colors.wine200,
    chartsWineBase: colors.wine200,
    chartsPinkHigh: colors.pink300,
    chartsPinkMedium: colors.pink200,
    chartsPinkLow: colors.pink100,
    chartsPinkBase: colors.pink0,
    chartsSeafoamHigh: colors.seafoam300,
    chartsSeafoamMedium: colors.seafoam200,
    chartsSeafoamLow: colors.seafoam100,
    chartsSeafoamBase: colors.seafoam0,
    chartsTangerineHigh: colors.tangerine300,
    chartsTangerineMedium: colors.tangerine200,
    chartsTangerineLow: colors.tangerine100,
    chartsTangerineBase: colors.tangerine0,
    chartsOliveHigh: colors.darkgreen300,
    chartsOliveMedium: colors.darkgreen200,
    chartsOliveLow: colors.darkgreen100,
    chartsOliveBase: colors.darkgreen0,
    chartsBlueHigh: colors.cyan300,
    chartsBlueMedium: colors.cyan200,
    chartsBlueLow: colors.cyan100,
    chartsBlueBase: colors.cyan00,
    chartsGreenHigh: colors.mudgreen600,
    chartsGreenMedium: colors.mudgreen400,
    chartsGreenLow: colors.mudgreen200,
    chartsGreenBase: colors.mudgreen100,
    chartsBrandContrast: colors.brandPrimaryActive,
    chartsBrandHigh: colors.brandPrimaryActive,
    chartsBrandMedium: colors.brandPrimaryHover,
    chartsBrandLow: colors.brandPrimary,
    chartsBrandBase: colors.brandPrimaryDisabled,
    chartsHeatmapHigh: colors.violet900,
    chartsHeatmapMedium: colors.violet500,
    chartsHeatmapLow: colors.violet200,
    chartsHeatmapBase: colors.gray100,
    chartsRedHigh: colors.red400,
    chartsRedMedium: colors.red200,
    chartsRedLow: colors.wine300,
    chartsRedBase: colors.wine100,
    chartsBrandHighAlpha: '#2200F999',
    chartsBrandMediumAlpha: '#917FFF99',
    chartsBrandLowAlpha: '#B0A7EA99',
    chartsBrandBaseAlpha: '#CAC3F166',
    chartsInformationHigh: colors.blue700,
    chartsGradientStart: colors.cyan200,
    chartsGradientEnd: colors.lavender200,
    navBgGradientTop: '#705EE40A',
    navBgGradientBottom: '#533FD100',
    chartsInformationMedium: colors.blue600,
    chartsInformationLow: colors.blue400,
    chartsInformationBase: colors.blue300,
    tagsCoralBg: colors.pink100,
    tagsCoralBorder: colors.pink200,
    tagsCoralText: colors.pink400,
    tagsBrandBg: colors.brandAccentTertiary,
    tagsBrandBorder: colors.brandPrimaryDisabled,
    tagsBrandText: colors.brandPrimary,
    tagsAccentBg: colors.blue0,
    tagsAccentBorder: colors.blue300,
    tagsAccentText: colors.blue700,
    tagsTangerineBg: colors.tangerine0,
    tagsTangerineBorder: colors.tangerine100,
    tagsTangerineText: colors.tangerine300,
    tagsSeafoamBg: colors.seafoam0,
    tagsSeafoamBorder: colors.seafoam100,
    tagsSeafoamText: colors.seafoam300,
    tagsTrueBlueBg: colors.trueblue0,
    tagsTrueBlueBorder: colors.trueblue100,
    tagsTrueBlueText: colors.trueblue300,
    tagsCobaltBlueBg: colors.cobalt0,
    tagsCobaltBlueBorder: colors.cobalt100,
    tagsCobaltBlueText: colors.cobalt300,
    tagsCyanBg: colors.cyan00,
    tagsCyanBorder: colors.cyan100,
    tagsCyanText: colors.cyan300,
    tagsDeepGreenBg: colors.darkgreen0,
    tagsDeepGreenBorder: colors.darkgreen100,
    tagsDeepGreenText: colors.darkgreen300,
    tagsOliveBg: colors.olive0,
    tagsOliveBorder: colors.olive100,
    tagsOliveText: colors.olive300,
    tagsLavenderBg: colors.lavender0,
    tagsLavenderBorder: colors.lavender100,
    tagsLavenderText: colors.lavender300,
    tagsBrownBg: colors.brown0,
    tagsBrownBorder: colors.brown200,
    tagsBrownText: colors.brown300,
    tagsTrueYellowBg: colors.trueyellow0,
    tagsTrueYellowBorder: colors.trueyellow100,
    tagsTrueYellowIcon: colors.trueyellow200,
    tagsTrueYellowText: colors.trueyellow300,
    colorPickerOrange: colors.orange500,
    colorPickerBlue: colors.trueblue100,
    colorPickerCobalt: colors.cobalt200,
    colorPickerTangerine: colors.tangerine300,
    colorPickerBrown: colors.brown300,
    colorPickerDarkGreen: colors.darkgreen300,
    colorPickerOlive: colors.olive300,
    colorPickerDefault: colors.gray1200,

    // Glossary Color Palette
    glossaryPaletteViolet: colors.violet400,
    glossaryPalettePurple: colors.violet500,
    glossaryPaletteLightBlue: colors.trueblue100,
    glossaryPaletteBlue: colors.trueblue300,
    glossaryPaletteTeal: colors.cyan200,
    glossaryPaletteGreen: colors.mudgreen500,
    glossaryPaletteLime: colors.olive200,
    glossaryPaletteLightOrange: colors.trueyellow200,
    glossaryPaletteMustard: colors.yellow600,
    glossaryPaletteOrange: colors.orange400,
    glossaryPalettePeach: colors.orange300,
    glossaryPaletteRed: colors.wine600,
    glossaryPaletteMagenta: colors.pink300,
    glossaryPaletteColdGrey: colors.gray600,
};

export default lightTheme;
